# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Menu layout
nav:
  main:
    - name: Install
      path: /install/
    - name: Translate
      path: /translate/
    - name: Themes
      path: /themes/
    - name: Plugins
      path: /plugins/
    - name: Code
      path: /code/external/
    - name: Contribute
      path: /contribute/
    - name: Add-Ons
      path: /addons/

  second:
    - name: Services
      path: /services/
    - name: Sites
      url: https://www.question2answer.org/sites.php
    - name: Q&A
      url: https://www.question2answer.org/qa/

  install:
    - name: Basic Install
      path: /install/
    - name: WordPress
      path: /install/wordpress/
    - name: Single Sign-On
      path: /install/single-sign-on/
    - name: Upgrading
      path: /install/upgrade/
    - name: Optimization
      path: /install/optimize/
    - name: Security
      path: /install/security/
    - name: .htaccess
      path: /install/htaccess/

  plugins:
    - name: Overview
      path: /plugins/
    - name: Modules
      path: /plugins/modules/
    - name: Layers
      path: /plugins/layers/
    - name: Overrides
      path: /plugins/overrides/
    - name: Plugin Tutorial
      path: /plugins/tutorial/

  code:
    - name: External
      path: /code/external/
    - name: Functions
      path: /code/functions/
    - name: App Structure
      path: /code/structure/

  contribute:
    - name: Issues
      path: /contribute/
    - name: Coding Style
      path: /contribute/coding-style/
    - name: Unit tests
      path: /contribute/unit-tests/
    - name: Documentation
      path: /contribute/docs/

  addons:
    - name: Translations
      path: /addons/translations/
    - name: Themes
      path: /addons/themes/
    - name: Plugins
      path: /addons/plugins/
    - name: Clients
      path: /addons/clients/

