# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty

# Build settings
markdown: kramdown

exclude: ['/vendor']

# Menu layout
nav:
  main:
    - name: Install
      path: /install-basic/
    - name: Add-Ons
      path: /addons/
    - name: Developers
      path: /developers/
    - name: Services
      path: /services/
  install:
    - name: Basic Install
      path: /install-basic/
    - name: WordPress
      path: /install-wordpress/
    - name: Single Sign-On
      path: /install-single-sign-on/
    - name: Optimization
      path: /install-optimize/
    - name: Security
      path: /install-security/
  developers:
    - name: Translate
      path: /developers-translate/
    - name: Themes
      path: /developers-themes/
    - name: External
      path: /developers-external/
    - name: Functions
      path: /developers-functions/
    - name: Plugins
      path: /developers-plugins/
    - name: Plugin Tutorial
      path: /developers-plugins-tutorial/
    - name: Modules
      path: /developers-modules/
    - name: Layers
      path: /developers-layers/
    - name: Overrides
      path: /developers-overrides/
