# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
# temporarily use redcarpet (instead of kramdown) so we can use 'startinline' option
markdown: redcarpet

kramdown:
  input: GFM

highlighter: rouge

# Menu layout
nav:
  main:
    - name: Install
      path: /install/
    - name: Translate
      path: /translate/
    - name: Themes
      path: /themes/
    - name: Plugins
      path: /plugins/
    - name: Code
      path: /code/external/
    - name: Add-Ons
      path: /addons/
    - name: Services
      path: /services/

  install:
    - name: Basic Install
      path: /install/
    - name: WordPress
      path: /install/wordpress/
    - name: Single Sign-On
      path: /install/single-sign-on/
    - name: Optimization
      path: /install/optimize/
    - name: Security
      path: /install/security/

  plugins:
    - name: Plugins
      path: /plugins/
    - name: Modules
      path: /plugins/modules/
    - name: Layers
      path: /plugins/layers/
    - name: Overrides
      path: /plugins/overrides/
    - name: Plugin Tutorial
      path: /plugins/tutorial/

  code:
    - name: External
      path: /code/external/
    - name: Functions
      path: /code/functions/

