# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty

# Build settings
markdown: kramdown

exclude: ['/vendor']

nav:
  main:
    - name: Install
      path: install-basic
    - name: Add-Ons
      path: addons
    - name: Developers
      path: developers
    - name: Services
      path: services
